# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: seed_migrator 0.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "seed_migrator"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Arthur Shagall", "Zach Belzer"]
  s.date = "2014-09-29"
  s.description = "Provides a clean way to handle updates to seed data post-launch."
  s.email = ["arthur.shagall@gmail.com", "zbelzer@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/generators/seed_migrator/create/USAGE",
    "lib/generators/seed_migrator/create/create_generator.rb",
    "lib/generators/seed_migrator/create/templates/data_update.rb",
    "lib/generators/seed_migrator/create/templates/data_update_migration.rb",
    "lib/generators/seed_migrator/helper.rb",
    "lib/generators/seed_migrator/install/USAGE",
    "lib/generators/seed_migrator/install/install_generator.rb",
    "lib/generators/seed_migrator/install/templates/data_update_module.rb",
    "lib/seed_migrator.rb",
    "lib/seed_migrator/seeds.rb",
    "lib/seed_migrator/update_class_loader.rb",
    "lib/seed_migrator/updater.rb"
  ]
  s.homepage = "https://github.com/HornsAndHooves"
  s.rubygems_version = "2.2.2"
  s.summary = "Handle post-release data updates through migrations"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 4.0"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 5.0"])
      s.add_runtime_dependency(%q<i18n>, ["> 0.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 4.0"])
      s.add_dependency(%q<activerecord>, ["~> 5.0"])
      s.add_dependency(%q<i18n>, ["> 0.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 4.0"])
    s.add_dependency(%q<activerecord>, ["~> 5.0"])
    s.add_dependency(%q<i18n>, ["> 0.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

